// ============================================
// Generated by SparseTensorCompiler
// Kernel: scheduled_compute
// Format-correctness reordering: not needed
// Optimization: interchange=ON
// Optimization: blocking=ON (size=32)
// Optimization order: I_B_I (Interchange -> Block -> Interchange)
// ============================================

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <time.h>
#include <math.h>

// ============================================
// SparseMatrix Structure (supports CSR and CSC)
// ============================================

typedef struct {
    int rows;
    int cols;
    int nnz;
    // CSR fields
    int* row_ptr;
    int* col_idx;
    // CSC fields (same memory, different interpretation)
    int* col_ptr;  // Same as row_ptr for CSC
    int* row_idx;  // Same as col_idx for CSC
    double* vals;
} SparseMatrix;

// ============================================
// Matrix Market Loader (COO -> CSR)
// ============================================

typedef struct {
    int r;
    int c;
    double v;
} Entry;

static void mm_strlower(char* s) {
    for (; *s; ++s) *s = (char)tolower((unsigned char)*s);
}

static int cmp_entry_row_col(const void* a, const void* b) {
    const Entry* ea = (const Entry*)a;
    const Entry* eb = (const Entry*)b;
    if (ea->r != eb->r) return (ea->r < eb->r) ? -1 : 1;
    if (ea->c != eb->c) return (ea->c < eb->c) ? -1 : 1;
    return 0;
}

static int cmp_entry_col_row(const void* a, const void* b) {
    const Entry* ea = (const Entry*)a;
    const Entry* eb = (const Entry*)b;
    if (ea->c != eb->c) return (ea->c < eb->c) ? -1 : 1;
    if (ea->r != eb->r) return (ea->r < eb->r) ? -1 : 1;
    return 0;
}

static SparseMatrix* mm_fail(FILE* f, Entry* entries, const char* msg) {
    if (msg) fprintf(stderr, "Error: %s\n", msg);
    if (entries) free(entries);
    if (f) fclose(f);
    return NULL;
}

SparseMatrix* load_matrix_market(const char* filename) {
    FILE* f = fopen(filename, "r");
    if (!f) {
        fprintf(stderr, "Error: Cannot open file %s\n", filename);
        return NULL;
    }

    char line[1024];
    char mm_object[64] = "matrix";
    char mm_format[64] = "coordinate";
    char mm_field[64] = "real";
    char mm_sym[64] = "general";

    if (!fgets(line, sizeof(line), f)) {
        return mm_fail(f, NULL, "Empty Matrix Market file");
    }

    if (strncmp(line, "%%MatrixMarket", 14) == 0) {
        char banner[32];
        if (sscanf(line, "%31s %63s %63s %63s %63s", banner, mm_object, mm_format, mm_field, mm_sym) != 5) {
            return mm_fail(f, NULL, "Invalid Matrix Market banner");
        }
        mm_strlower(mm_object);
        mm_strlower(mm_format);
        mm_strlower(mm_field);
        mm_strlower(mm_sym);
        if (strcmp(mm_object, "matrix") != 0) {
            return mm_fail(f, NULL, "Only Matrix Market 'matrix' object is supported");
        }
        if (strcmp(mm_format, "coordinate") != 0) {
            return mm_fail(f, NULL, "Only coordinate format is supported");
        }
        if (strcmp(mm_field, "real") != 0 && strcmp(mm_field, "integer") != 0 && strcmp(mm_field, "pattern") != 0) {
            return mm_fail(f, NULL, "Only real/integer/pattern fields are supported");
        }
        if (strcmp(mm_sym, "general") != 0 && strcmp(mm_sym, "symmetric") != 0 && strcmp(mm_sym, "skew-symmetric") != 0) {
            return mm_fail(f, NULL, "Only general/symmetric/skew-symmetric are supported");
        }
        if (!fgets(line, sizeof(line), f)) {
            return mm_fail(f, NULL, "Unexpected end of file after banner");
        }
    }

    // Skip comment lines to find dimensions
    while (line[0] == '%') {
        if (!fgets(line, sizeof(line), f)) {
            return mm_fail(f, NULL, "Unexpected end of file before dimensions");
        }
    }

    // Parse dimensions
    int rows, cols, nnz_stored;
    if (sscanf(line, "%d %d %d", &rows, &cols, &nnz_stored) != 3) {
        return mm_fail(f, NULL, "Invalid dimension line");
    }

    if ((strcmp(mm_sym, "symmetric") == 0 || strcmp(mm_sym, "skew-symmetric") == 0) && rows != cols) {
        return mm_fail(f, NULL, "Symmetric matrices must be square");
    }

    int max_entries = nnz_stored;
    if (strcmp(mm_sym, "symmetric") == 0 || strcmp(mm_sym, "skew-symmetric") == 0) {
        max_entries = nnz_stored * 2;
    }
    Entry* entries = (Entry*)malloc(max_entries * sizeof(Entry));
    if (!entries) {
        return mm_fail(f, NULL, "Failed to allocate entries");
    }
    int nnz_entries = 0;

    // Read COO entries (1-indexed in file, convert to 0-indexed)
    for (int i = 0; i < nnz_stored; i++) {
        int r, c;
        double v = 1.0;
        if (strcmp(mm_field, "pattern") == 0) {
            if (fscanf(f, "%d %d", &r, &c) != 2) {
                return mm_fail(f, entries, "Failed to read pattern entry");
            }
        } else if (strcmp(mm_field, "integer") == 0) {
            long long v_int;
            if (fscanf(f, "%d %d %lld", &r, &c, &v_int) != 3) {
                return mm_fail(f, entries, "Failed to read integer entry");
            }
            v = (double)v_int;
        } else {
            if (fscanf(f, "%d %d %lf", &r, &c, &v) != 3) {
                return mm_fail(f, entries, "Failed to read real entry");
            }
        }
        r--;  // Convert to 0-indexed
        c--;  // Convert to 0-indexed
        entries[nnz_entries].r = r;
        entries[nnz_entries].c = c;
        entries[nnz_entries].v = v;
        nnz_entries++;

        if ((strcmp(mm_sym, "symmetric") == 0 || strcmp(mm_sym, "skew-symmetric") == 0) && r != c) {
            double v2 = (strcmp(mm_sym, "skew-symmetric") == 0) ? -v : v;
            entries[nnz_entries].r = c;
            entries[nnz_entries].c = r;
            entries[nnz_entries].v = v2;
            nnz_entries++;
        }
    }
    fclose(f);

    // Canonicalize ordering for stable baselines
    qsort(entries, nnz_entries, sizeof(Entry), cmp_entry_row_col);

    // Merge duplicate coordinates by summing values
    int nnz_unique = 0;
    for (int i = 0; i < nnz_entries; i++) {
        if (nnz_unique == 0 || entries[i].r != entries[nnz_unique - 1].r || entries[i].c != entries[nnz_unique - 1].c) {
            entries[nnz_unique++] = entries[i];
        } else {
            entries[nnz_unique - 1].v += entries[i].v;
        }
    }
    int nnz = nnz_unique;

    // Convert COO to CSR (row-major)
    SparseMatrix* mat = (SparseMatrix*)malloc(sizeof(SparseMatrix));
    mat->rows = rows;
    mat->cols = cols;
    mat->nnz = nnz;
    mat->row_ptr = (int*)calloc(rows + 1, sizeof(int));
    mat->col_idx = (int*)malloc(nnz * sizeof(int));
    mat->vals = (double*)malloc(nnz * sizeof(double));
    // CSC aliases (point to same memory as CSR)
    mat->col_ptr = mat->row_ptr;
    mat->row_idx = mat->col_idx;

    // Count nnz per row
    for (int i = 0; i < nnz; i++) {
        mat->row_ptr[entries[i].r + 1]++;
    }

    // Cumulative sum to get row_ptr
    for (int i = 0; i < rows; i++) {
        mat->row_ptr[i + 1] += mat->row_ptr[i];
    }

    // Fill col_idx and vals
    int* row_counters = (int*)calloc(rows, sizeof(int));
    for (int i = 0; i < nnz; i++) {
        int row = entries[i].r;
        int dest = mat->row_ptr[row] + row_counters[row];
        mat->col_idx[dest] = entries[i].c;
        mat->vals[dest] = entries[i].v;
        row_counters[row]++;
    }

    // Cleanup
    free(entries);
    free(row_counters);

    return mat;
}

void free_sparse(SparseMatrix* mat) {
    if (mat) {
        free(mat->row_ptr);
        free(mat->col_idx);
        free(mat->vals);
        free(mat);
    }
}

// ============================================
// Timing Utilities
// ============================================

double get_time_ms() {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec * 1000.0 + ts.tv_nsec / 1000000.0;
}

// ============================================
// Matrix Feature Extraction (Tier 1)
// ============================================

void compute_features(const SparseMatrix* A) {
    // Group 1: Dimensions & Density
    int m = A->rows;
    int n = A->cols;
    int nz = A->nnz;
    double density = nz / ((double)m * n);
    double avg_nnz_row = (double)nz / m;
    double avg_nnz_col = (double)nz / n;
    double aspect_ratio = (double)m / n;

    // Column counts
    int* col_nnz = (int*)calloc(n, sizeof(int));
    for (int p = 0; p < nz; p++) col_nnz[A->col_idx[p]]++;

    // Group 2: Row irregularity
    double row_var_sum = 0.0;
    int max_row_len = 0;
    int min_row_len = (m > 0) ? (A->row_ptr[1] - A->row_ptr[0]) : 0;
    for (int i = 0; i < m; i++) {
        int rlen = A->row_ptr[i+1] - A->row_ptr[i];
        double diff = rlen - avg_nnz_row;
        row_var_sum += diff * diff;
        if (rlen > max_row_len) max_row_len = rlen;
        if (rlen < min_row_len) min_row_len = rlen;
    }
    double row_variance = row_var_sum / m;
    double row_cv = sqrt(row_variance) / (avg_nnz_row + 1e-9);

    // Column irregularity
    double col_var_sum = 0.0;
    for (int j = 0; j < n; j++) {
        double diff = col_nnz[j] - avg_nnz_col;
        col_var_sum += diff * diff;
    }
    double col_variance = col_var_sum / n;
    double col_cv = sqrt(col_variance) / (avg_nnz_col + 1e-9);

    // Groups 3 & 4: Bandwidth, row span, clustering (O(nnz) pass)
    int bandwidth = 0;
    double span_sum = 0.0;
    int nonempty_rows = 0;
    long total_runs = 0;
    long total_run_length = 0;
    long total_gaps = 0;
    double gap_sum = 0.0;
    long adjacent_count = 0;
    for (int i = 0; i < m; i++) {
        int start = A->row_ptr[i];
        int end = A->row_ptr[i+1];
        int rlen = end - start;
        if (rlen == 0) continue;
        nonempty_rows++;
        int min_col = A->col_idx[start];
        int max_col = A->col_idx[start];
        int runs = 1;
        for (int p = start + 1; p < end; p++) {
            int c = A->col_idx[p];
            if (c < min_col) min_col = c;
            if (c > max_col) max_col = c;
            int gap = A->col_idx[p] - A->col_idx[p-1];
            if (gap < 0) gap = -gap;
            if (gap != 1) runs++;
            else adjacent_count++;
            gap_sum += gap;
            total_gaps++;
        }
        total_runs += runs;
        total_run_length += rlen;
        span_sum += (max_col - min_col + 1);
        int bw = (i > max_col) ? (i - min_col) : (max_col - i);
        if (bw > bandwidth) bandwidth = bw;
    }
    double avg_row_span = (nonempty_rows > 0) ? span_sum / nonempty_rows : 0.0;
    double avg_runs_per_row = (nonempty_rows > 0) ? (double)total_runs / nonempty_rows : 0.0;
    double avg_run_length = (total_runs > 0) ? (double)total_run_length / total_runs : 0.0;
    double avg_gap = (total_gaps > 0) ? gap_sum / total_gaps : 0.0;
    double frac_adjacent = (total_gaps > 0) ? (double)adjacent_count / total_gaps : 0.0;

    // Group 5: Column entropy
    double entropy = 0.0;
    for (int j = 0; j < n; j++) {
        if (col_nnz[j] > 0) {
            double p = (double)col_nnz[j] / nz;
            entropy -= p * log(p);
        }
    }
    double norm_entropy = (n > 1) ? entropy / log(n) : 0.0;

    // Group 6: Cross-row spatial locality
    double col_pair_sum = 0.0;
    for (int j = 0; j < n; j++) {
        col_pair_sum += (double)col_nnz[j] * (col_nnz[j] - 1) / 2.0;
    }
    double R = (double)m;
    double avg_entry_matches = (R > 1) ? 2.0 * col_pair_sum / (R * (R - 1)) : 0.0;

    // Print features with FEATURE: prefix
    printf("FEATURE: m_rows=%d\n", m);
    printf("FEATURE: n_cols=%d\n", n);
    printf("FEATURE: aspect_ratio=%.4f\n", aspect_ratio);
    printf("FEATURE: nnz=%d\n", nz);
    printf("FEATURE: density=%.4e\n", density);
    printf("FEATURE: avg_nnz_row=%.4f\n", avg_nnz_row);
    printf("FEATURE: avg_nnz_col=%.4f\n", avg_nnz_col);
    printf("FEATURE: row_variance=%.4f\n", row_variance);
    printf("FEATURE: row_cv=%.4f\n", row_cv);
    printf("FEATURE: max_row_length=%d\n", max_row_len);
    printf("FEATURE: min_row_length=%d\n", min_row_len);
    printf("FEATURE: col_variance=%.4f\n", col_variance);
    printf("FEATURE: col_cv=%.4f\n", col_cv);
    printf("FEATURE: bandwidth=%d\n", bandwidth);
    printf("FEATURE: avg_row_span=%.2f\n", avg_row_span);
    printf("FEATURE: avg_runs_per_row=%.2f\n", avg_runs_per_row);
    printf("FEATURE: avg_run_length=%.2f\n", avg_run_length);
    printf("FEATURE: avg_gap=%.2f\n", avg_gap);
    printf("FEATURE: frac_adjacent=%.4f\n", frac_adjacent);
    printf("FEATURE: normalized_entropy=%.4f\n", norm_entropy);
    printf("FEATURE: avg_entry_matches=%.2f\n", avg_entry_matches);

    free(col_nnz);
}

// ============================================
// Optimized Kernel
// ============================================

void compute(const SparseMatrix* A, const double** B, double** C, int N_j) {
    // Optimization: loop interchange applied
    // Optimization: loop blocking (block_size=32)
    for (int i = 0; i < A->rows; i++) {
        for (int j_block = 0; j_block < (N_j + 31) / 32; j_block++) {
            int j_start = j_block * 32;
            int j_end = (j_start + 32 < N_j) ? j_start + 32 : N_j;
            for (int j = j_start; j < j_end; j++) {
                for (int pA = A->row_ptr[i]; pA < A->row_ptr[i + 1]; pA++) {
                    int k = A->col_idx[pA];
                    C[i][j] += A->vals[pA] * B[k][j];
                }
            }
        }
    }
}

// ============================================
// Reference Kernel (naive, for verification)
// ============================================

void reference(const SparseMatrix* A, const double** B, double** C, int N_j) {
    for (int i = 0; i < A->rows; i++) {
        for (int j_block = 0; j_block < (N_j + 31) / 32; j_block++) {
            int j_start = j_block * 32;
            int j_end = (j_start + 32 < N_j) ? j_start + 32 : N_j;
            for (int j = j_start; j < j_end; j++) {
                for (int pA = A->row_ptr[i]; pA < A->row_ptr[i + 1]; pA++) {
                    int k = A->col_idx[pA];
                    C[i][j] += A->vals[pA] * B[k][j];
                }
            }
        }
    }
}

// ============================================
// Main Function
// ============================================

int main(int argc, char** argv) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <matrix.mtx> [iterations]\n", argv[0]);
        return 1;
    }

    int iterations = 100;
    if (argc >= 3) {
        iterations = atoi(argv[2]);
        if (iterations <= 0) {
            fprintf(stderr, "Error: iterations must be > 0\n");
            return 1;
        }
    }

    // Deterministic initialization for reproducible benchmarks
    srand(42);

    // Load sparse matrix A
    SparseMatrix* A = load_matrix_market(argv[1]);
    if (!A) {
        fprintf(stderr, "Failed to load matrix A\n");
        return 1;
    }

    int N_j = 50;

    // Allocate dense matrix B
    double** B = (double**)malloc(A->cols * sizeof(double*));
    for (int _i = 0; _i < A->cols; _i++) {
        B[_i] = (double*)malloc(N_j * sizeof(double));
        for (int _j = 0; _j < N_j; _j++) {
            B[_i][_j] = (double)rand() / RAND_MAX;
        }
    }

    // Allocate output matrix C
    double** C = (double**)malloc(A->rows * sizeof(double*));
    double** C_ref = (double**)malloc(A->rows * sizeof(double*));
    for (int _i = 0; _i < A->rows; _i++) {
        C[_i] = (double*)calloc(N_j, sizeof(double));
        C_ref[_i] = (double*)calloc(N_j, sizeof(double));
    }

    // Warmup
    compute(A, B, C, N_j);

    // Benchmark with per-iteration timing
    double* iter_times = (double*)malloc(iterations * sizeof(double));

    for (int iter = 0; iter < iterations; iter++) {
        for (int _i = 0; _i < A->rows; _i++) {
            memset(C[_i], 0, N_j * sizeof(double));
        }
        double iter_start = get_time_ms();
        compute(A, B, C, N_j);
        double iter_end = get_time_ms();
        iter_times[iter] = iter_end - iter_start;
    }

    // Compute timing statistics
    double total_time = 0.0;
    double min_time = iter_times[0];
    double max_time = iter_times[0];
    for (int iter = 0; iter < iterations; iter++) {
        total_time += iter_times[iter];
        if (iter_times[iter] < min_time) min_time = iter_times[iter];
        if (iter_times[iter] > max_time) max_time = iter_times[iter];
    }
    double avg_time = total_time / iterations;

    // Compute standard deviation
    double variance = 0.0;
    for (int iter = 0; iter < iterations; iter++) {
        double diff = iter_times[iter] - avg_time;
        variance += diff * diff;
    }
    variance /= iterations;
    double stddev = sqrt(variance);
    double variance_pct = (avg_time > 0) ? (stddev / avg_time * 100.0) : 0.0;

    // Verify correctness
    reference(A, B, C_ref, N_j);
    double max_error = 0.0;
    for (int _i = 0; _i < A->rows; _i++) {
        for (int _j = 0; _j < N_j; _j++) {
            double err = C[_i][_j] - C_ref[_i][_j];
            if (err < 0) err = -err;
            if (err > max_error) max_error = err;
        }
    }

    // Report results
    printf("Matrix: %s (%d x %d, %d nnz)\n", argv[1], A->rows, A->cols, A->nnz);
    printf("Iterations: %d\n", iterations);
    printf("Total time: %.2f ms\n", total_time);
    printf("Avg time per iteration: %.4f ms\n", avg_time);
    printf("Min time per iteration: %.4f ms\n", min_time);
    printf("Max time per iteration: %.4f ms\n", max_time);
    printf("Stddev time: %.4f ms\n", stddev);
    printf("Variance: %.2f%%\n", variance_pct);
    printf("Max error vs reference: %e\n", max_error);

    compute_features(A);

    // Cleanup
    free(iter_times);
    for (int _i = 0; _i < A->cols; _i++) free(B[_i]);
    free(B);
    for (int _i = 0; _i < A->rows; _i++) {
        free(C[_i]);
        free(C_ref[_i]);
    }
    free(C);
    free(C_ref);
    free_sparse(A);

    return 0;
}
