#include "codegen.h"

#include <algorithm>
#include <fstream>
#include <sstream>
#include <set>

namespace codegen {

void CodeGenerator::generate(const sparseir::scheduled::Compute& compute,
                             const opt::OptConfig& config) {
    prepareComputeEmission(compute, config);

    emitHeader();
    emitStructDefinitions();
    emitMatrixMarketLoader();
    emitTimingHarness();
    emitFeatureExtraction();
    if (isSparseOutputMode()) {
        emitSparseOutputHelpers();
    }
    emitKernel();
    emitReferenceKernel();
    emitVerification();
    emitMain();

    resetComputeEmission();
}

std::string generateCode(const sparseir::scheduled::Compute& compute,
                         const opt::OptConfig& config) {
    std::ostringstream oss;
    CodeGenerator gen(oss);
    gen.generate(compute, config);
    return oss.str();
}

bool generateToFile(const sparseir::scheduled::Compute& compute,
                    const opt::OptConfig& config,
                    const std::string& filename) {
    std::ofstream file(filename);
    if (!file.is_open()) {
        return false;
    }

    CodeGenerator gen(file);
    gen.generate(compute, config);
    file.close();
    return true;
}

void CodeGenerator::emitHeader() {
    emitLine("// ============================================");
    emitLine("// Generated by SparseTensorCompiler");
    emitLine("// Kernel: scheduled_compute");

    const auto& optimizations = getActiveOptimizations();
    bool reorderingApplied = optimizations.reorderingApplied;
    bool interchangeApplied = optimizations.interchangeApplied;
    bool blockingApplied = optimizations.blockingApplied;

    emitLine("// Format-correctness reordering: " +
             std::string(reorderingApplied ? "APPLIED" : "not needed"));
    emitLine("// Optimization: interchange=" + std::string(interchangeApplied ? "ON" : "OFF"));
    if (blockingApplied) {
        if (optimizations.blocking2DApplied) {
            std::string sizes;
            for (size_t i = 0; i < optimizations.tiledIndices.size(); i++) {
                if (i > 0) sizes += ", ";
                sizes += optimizations.tiledIndices[i] + "=" +
                         std::to_string(optimizations.blockSizes[i]);
            }
            emitLine("// Optimization: blocking=ON 2D (" + sizes + ")");
        } else {
            emitLine("// Optimization: blocking=ON (size=" +
                     std::to_string(optimizations.blockSize) + ")");
        }
    } else {
        emitLine("// Optimization: blocking=OFF");
    }

    if (config_->enableInterchange && config_->enableBlocking) {
        std::string orderStr;
        switch (config_->order) {
            case opt::OptOrder::I_THEN_B:
                orderStr = "I_THEN_B (Interchange -> Block)";
                break;
            case opt::OptOrder::B_THEN_I:
                orderStr = "B_THEN_I (Block -> Interchange)";
                break;
            case opt::OptOrder::I_B_I:
                orderStr = "I_B_I (Interchange -> Block -> Interchange)";
                break;
        }
        emitLine("// Optimization order: " + orderStr);
    }

    emitLine("// ============================================");
    emitLine();
    emitLine("#include <stdio.h>");
    emitLine("#include <stdlib.h>");
    emitLine("#include <string.h>");
    emitLine("#include <ctype.h>");
    emitLine("#include <time.h>");
    emitLine("#include <math.h>");
    emitLine();
}

void CodeGenerator::emitStructDefinitions() {
    emitLine("// ============================================");
    emitLine("// SparseMatrix Structure (supports CSR and CSC)");
    emitLine("// ============================================");
    emitLine();
    emitLine("typedef struct {");
    increaseIndent();
    emitLine("int rows;");
    emitLine("int cols;");
    emitLine("int nnz;");
    emitLine("// CSR fields");
    emitLine("int* row_ptr;");
    emitLine("int* col_idx;");
    emitLine("// CSC fields (same memory, different interpretation)");
    emitLine("int* col_ptr;  // Same as row_ptr for CSC");
    emitLine("int* row_idx;  // Same as col_idx for CSC");
    emitLine("double* vals;");
    decreaseIndent();
    emitLine("} SparseMatrix;");
    emitLine();
}

void CodeGenerator::emitMatrixMarketLoader() {
    ir::Format sparseFormat = ir::Format::CSR;
    for (const auto& tensor : getActiveInputs()) {
        if (tensor.format == ir::Format::CSR || tensor.format == ir::Format::CSC) {
            sparseFormat = tensor.format;
            break;
        }
    }

    std::string formatStr = (sparseFormat == ir::Format::CSC) ? "CSC" : "CSR";

    emitLine("// ============================================");
    emitLine("// Matrix Market Loader (COO -> " + formatStr + ")");
    emitLine("// ============================================");
    emitLine();
    emitLine("typedef struct {");
    increaseIndent();
    emitLine("int r;");
    emitLine("int c;");
    emitLine("double v;");
    decreaseIndent();
    emitLine("} Entry;");
    emitLine();
    emitLine("static void mm_strlower(char* s) {");
    increaseIndent();
    emitLine("for (; *s; ++s) *s = (char)tolower((unsigned char)*s);");
    decreaseIndent();
    emitLine("}");
    emitLine();
    emitLine("static int cmp_entry_row_col(const void* a, const void* b) {");
    increaseIndent();
    emitLine("const Entry* ea = (const Entry*)a;");
    emitLine("const Entry* eb = (const Entry*)b;");
    emitLine("if (ea->r != eb->r) return (ea->r < eb->r) ? -1 : 1;");
    emitLine("if (ea->c != eb->c) return (ea->c < eb->c) ? -1 : 1;");
    emitLine("return 0;");
    decreaseIndent();
    emitLine("}");
    emitLine();
    emitLine("static int cmp_entry_col_row(const void* a, const void* b) {");
    increaseIndent();
    emitLine("const Entry* ea = (const Entry*)a;");
    emitLine("const Entry* eb = (const Entry*)b;");
    emitLine("if (ea->c != eb->c) return (ea->c < eb->c) ? -1 : 1;");
    emitLine("if (ea->r != eb->r) return (ea->r < eb->r) ? -1 : 1;");
    emitLine("return 0;");
    decreaseIndent();
    emitLine("}");
    emitLine();
    emitLine("static SparseMatrix* mm_fail(FILE* f, Entry* entries, const char* msg) {");
    increaseIndent();
    emitLine("if (msg) fprintf(stderr, \"Error: %s\\n\", msg);");
    emitLine("if (entries) free(entries);");
    emitLine("if (f) fclose(f);");
    emitLine("return NULL;");
    decreaseIndent();
    emitLine("}");
    emitLine();
    emitLine("SparseMatrix* load_matrix_market(const char* filename) {");
    increaseIndent();

    emitLine("FILE* f = fopen(filename, \"r\");");
    emitLine("if (!f) {");
    increaseIndent();
    emitLine("fprintf(stderr, \"Error: Cannot open file %s\\n\", filename);");
    emitLine("return NULL;");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitLine("char line[1024];");
    emitLine("char mm_object[64] = \"matrix\";");
    emitLine("char mm_format[64] = \"coordinate\";");
    emitLine("char mm_field[64] = \"real\";");
    emitLine("char mm_sym[64] = \"general\";");
    emitLine();

    emitLine("if (!fgets(line, sizeof(line), f)) {");
    increaseIndent();
    emitLine("return mm_fail(f, NULL, \"Empty Matrix Market file\");");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitLine("if (strncmp(line, \"%%MatrixMarket\", 14) == 0) {");
    increaseIndent();
    emitLine("char banner[32];");
    emitLine("if (sscanf(line, \"%31s %63s %63s %63s %63s\", banner, mm_object, mm_format, mm_field, mm_sym) != 5) {");
    increaseIndent();
    emitLine("return mm_fail(f, NULL, \"Invalid Matrix Market banner\");");
    decreaseIndent();
    emitLine("}");
    emitLine("mm_strlower(mm_object);");
    emitLine("mm_strlower(mm_format);");
    emitLine("mm_strlower(mm_field);");
    emitLine("mm_strlower(mm_sym);");
    emitLine("if (strcmp(mm_object, \"matrix\") != 0) {");
    increaseIndent();
    emitLine("return mm_fail(f, NULL, \"Only Matrix Market 'matrix' object is supported\");");
    decreaseIndent();
    emitLine("}");
    emitLine("if (strcmp(mm_format, \"coordinate\") != 0) {");
    increaseIndent();
    emitLine("return mm_fail(f, NULL, \"Only coordinate format is supported\");");
    decreaseIndent();
    emitLine("}");
    emitLine("if (strcmp(mm_field, \"real\") != 0 && strcmp(mm_field, \"integer\") != 0 && strcmp(mm_field, \"pattern\") != 0) {");
    increaseIndent();
    emitLine("return mm_fail(f, NULL, \"Only real/integer/pattern fields are supported\");");
    decreaseIndent();
    emitLine("}");
    emitLine("if (strcmp(mm_sym, \"general\") != 0 && strcmp(mm_sym, \"symmetric\") != 0 && strcmp(mm_sym, \"skew-symmetric\") != 0) {");
    increaseIndent();
    emitLine("return mm_fail(f, NULL, \"Only general/symmetric/skew-symmetric are supported\");");
    decreaseIndent();
    emitLine("}");
    emitLine("if (!fgets(line, sizeof(line), f)) {");
    increaseIndent();
    emitLine("return mm_fail(f, NULL, \"Unexpected end of file after banner\");");
    decreaseIndent();
    emitLine("}");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitLine("// Skip comment lines to find dimensions");
    emitLine("while (line[0] == '%') {");
    increaseIndent();
    emitLine("if (!fgets(line, sizeof(line), f)) {");
    increaseIndent();
    emitLine("return mm_fail(f, NULL, \"Unexpected end of file before dimensions\");");
    decreaseIndent();
    emitLine("}");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitLine("// Parse dimensions");
    emitLine("int rows, cols, nnz_stored;");
    emitLine("if (sscanf(line, \"%d %d %d\", &rows, &cols, &nnz_stored) != 3) {");
    increaseIndent();
    emitLine("return mm_fail(f, NULL, \"Invalid dimension line\");");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitLine("if ((strcmp(mm_sym, \"symmetric\") == 0 || strcmp(mm_sym, \"skew-symmetric\") == 0) && rows != cols) {");
    increaseIndent();
    emitLine("return mm_fail(f, NULL, \"Symmetric matrices must be square\");");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitLine("int max_entries = nnz_stored;");
    emitLine("if (strcmp(mm_sym, \"symmetric\") == 0 || strcmp(mm_sym, \"skew-symmetric\") == 0) {");
    increaseIndent();
    emitLine("max_entries = nnz_stored * 2;");
    decreaseIndent();
    emitLine("}");
    emitLine("Entry* entries = (Entry*)malloc(max_entries * sizeof(Entry));");
    emitLine("if (!entries) {");
    increaseIndent();
    emitLine("return mm_fail(f, NULL, \"Failed to allocate entries\");");
    decreaseIndent();
    emitLine("}");
    emitLine("int nnz_entries = 0;");
    emitLine();

    emitLine("// Read COO entries (1-indexed in file, convert to 0-indexed)");
    emitLine("for (int i = 0; i < nnz_stored; i++) {");
    increaseIndent();
    emitLine("int r, c;");
    emitLine("double v = 1.0;");
    emitLine("if (strcmp(mm_field, \"pattern\") == 0) {");
    increaseIndent();
    emitLine("if (fscanf(f, \"%d %d\", &r, &c) != 2) {");
    increaseIndent();
    emitLine("return mm_fail(f, entries, \"Failed to read pattern entry\");");
    decreaseIndent();
    emitLine("}");
    decreaseIndent();
    emitLine("} else if (strcmp(mm_field, \"integer\") == 0) {");
    increaseIndent();
    emitLine("long long v_int;");
    emitLine("if (fscanf(f, \"%d %d %lld\", &r, &c, &v_int) != 3) {");
    increaseIndent();
    emitLine("return mm_fail(f, entries, \"Failed to read integer entry\");");
    decreaseIndent();
    emitLine("}");
    emitLine("v = (double)v_int;");
    decreaseIndent();
    emitLine("} else {");
    increaseIndent();
    emitLine("if (fscanf(f, \"%d %d %lf\", &r, &c, &v) != 3) {");
    increaseIndent();
    emitLine("return mm_fail(f, entries, \"Failed to read real entry\");");
    decreaseIndent();
    emitLine("}");
    decreaseIndent();
    emitLine("}");
    emitLine("r--;  // Convert to 0-indexed");
    emitLine("c--;  // Convert to 0-indexed");
    emitLine("entries[nnz_entries].r = r;");
    emitLine("entries[nnz_entries].c = c;");
    emitLine("entries[nnz_entries].v = v;");
    emitLine("nnz_entries++;");
    emitLine();
    emitLine("if ((strcmp(mm_sym, \"symmetric\") == 0 || strcmp(mm_sym, \"skew-symmetric\") == 0) && r != c) {");
    increaseIndent();
    emitLine("double v2 = (strcmp(mm_sym, \"skew-symmetric\") == 0) ? -v : v;");
    emitLine("entries[nnz_entries].r = c;");
    emitLine("entries[nnz_entries].c = r;");
    emitLine("entries[nnz_entries].v = v2;");
    emitLine("nnz_entries++;");
    decreaseIndent();
    emitLine("}");
    decreaseIndent();
    emitLine("}");
    emitLine("fclose(f);");
    emitLine();

    emitLine("// Canonicalize ordering for stable baselines");
    if (sparseFormat == ir::Format::CSC) {
        emitLine("qsort(entries, nnz_entries, sizeof(Entry), cmp_entry_col_row);");
    } else {
        emitLine("qsort(entries, nnz_entries, sizeof(Entry), cmp_entry_row_col);");
    }
    emitLine();

    emitLine("// Merge duplicate coordinates by summing values");
    emitLine("int nnz_unique = 0;");
    emitLine("for (int i = 0; i < nnz_entries; i++) {");
    increaseIndent();
    emitLine("if (nnz_unique == 0 || entries[i].r != entries[nnz_unique - 1].r || entries[i].c != entries[nnz_unique - 1].c) {");
    increaseIndent();
    emitLine("entries[nnz_unique++] = entries[i];");
    decreaseIndent();
    emitLine("} else {");
    increaseIndent();
    emitLine("entries[nnz_unique - 1].v += entries[i].v;");
    decreaseIndent();
    emitLine("}");
    decreaseIndent();
    emitLine("}");
    emitLine("int nnz = nnz_unique;");
    emitLine();

    if (sparseFormat == ir::Format::CSC) {
        emitCSCConversion();
    } else {
        emitCSRConversion();
    }
    emitLine();

    emitLine("return mat;");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitLine("void free_sparse(SparseMatrix* mat) {");
    increaseIndent();
    emitLine("if (mat) {");
    increaseIndent();
    emitLine("free(mat->row_ptr);");
    emitLine("free(mat->col_idx);");
    emitLine("free(mat->vals);");
    emitLine("free(mat);");
    decreaseIndent();
    emitLine("}");
    decreaseIndent();
    emitLine("}");
    emitLine();
}

void CodeGenerator::emitTimingHarness() {
    emitLine("// ============================================");
    emitLine("// Timing Utilities");
    emitLine("// ============================================");
    emitLine();
    emitLine("double get_time_ms() {");
    increaseIndent();
    emitLine("struct timespec ts;");
    emitLine("clock_gettime(CLOCK_MONOTONIC, &ts);");
    emitLine("return ts.tv_sec * 1000.0 + ts.tv_nsec / 1000000.0;");
    decreaseIndent();
    emitLine("}");
    emitLine();
}

void CodeGenerator::emitTimingStatistics() {
    emitLine("// Compute timing statistics");
    emitLine("double total_time = 0.0;");
    emitLine("double min_time = iter_times[0];");
    emitLine("double max_time = iter_times[0];");
    emitLine("for (int iter = 0; iter < iterations; iter++) {");
    increaseIndent();
    emitLine("total_time += iter_times[iter];");
    emitLine("if (iter_times[iter] < min_time) min_time = iter_times[iter];");
    emitLine("if (iter_times[iter] > max_time) max_time = iter_times[iter];");
    decreaseIndent();
    emitLine("}");
    emitLine("double avg_time = total_time / iterations;");
    emitLine();

    emitLine("// Compute standard deviation");
    emitLine("double variance = 0.0;");
    emitLine("for (int iter = 0; iter < iterations; iter++) {");
    increaseIndent();
    emitLine("double diff = iter_times[iter] - avg_time;");
    emitLine("variance += diff * diff;");
    decreaseIndent();
    emitLine("}");
    emitLine("variance /= iterations;");
    emitLine("double stddev = sqrt(variance);");
    emitLine("double variance_pct = (avg_time > 0) ? (stddev / avg_time * 100.0) : 0.0;");
    emitLine();
}

void CodeGenerator::emitFeatureExtraction() {
    emitLine("// ============================================");
    emitLine("// Matrix Feature Extraction (Tier 1)");
    emitLine("// ============================================");
    emitLine();
    emitLine("void compute_features(const SparseMatrix* A) {");
    increaseIndent();
    emitLine("// Group 1: Dimensions & Density");
    emitLine("int m = A->rows;");
    emitLine("int n = A->cols;");
    emitLine("int nz = A->nnz;");
    emitLine("double density = nz / ((double)m * n);");
    emitLine("double avg_nnz_row = (double)nz / m;");
    emitLine("double avg_nnz_col = (double)nz / n;");
    emitLine("double aspect_ratio = (double)m / n;");
    emitLine();
    emitLine("// Column counts");
    emitLine("int* col_nnz = (int*)calloc(n, sizeof(int));");
    emitLine("for (int p = 0; p < nz; p++) col_nnz[A->col_idx[p]]++;");
    emitLine();
    emitLine("// Group 2: Row irregularity");
    emitLine("double row_var_sum = 0.0;");
    emitLine("int max_row_len = 0;");
    emitLine("int min_row_len = (m > 0) ? (A->row_ptr[1] - A->row_ptr[0]) : 0;");
    emitLine("for (int i = 0; i < m; i++) {");
    increaseIndent();
    emitLine("int rlen = A->row_ptr[i+1] - A->row_ptr[i];");
    emitLine("double diff = rlen - avg_nnz_row;");
    emitLine("row_var_sum += diff * diff;");
    emitLine("if (rlen > max_row_len) max_row_len = rlen;");
    emitLine("if (rlen < min_row_len) min_row_len = rlen;");
    decreaseIndent();
    emitLine("}");
    emitLine("double row_variance = row_var_sum / m;");
    emitLine("double row_cv = sqrt(row_variance) / (avg_nnz_row + 1e-9);");
    emitLine();
    emitLine("// Column irregularity");
    emitLine("double col_var_sum = 0.0;");
    emitLine("for (int j = 0; j < n; j++) {");
    increaseIndent();
    emitLine("double diff = col_nnz[j] - avg_nnz_col;");
    emitLine("col_var_sum += diff * diff;");
    decreaseIndent();
    emitLine("}");
    emitLine("double col_variance = col_var_sum / n;");
    emitLine("double col_cv = sqrt(col_variance) / (avg_nnz_col + 1e-9);");
    emitLine();
    emitLine("// Groups 3 & 4: Bandwidth, row span, clustering (O(nnz) pass)");
    emitLine("int bandwidth = 0;");
    emitLine("double span_sum = 0.0;");
    emitLine("int nonempty_rows = 0;");
    emitLine("long total_runs = 0;");
    emitLine("long total_run_length = 0;");
    emitLine("long total_gaps = 0;");
    emitLine("double gap_sum = 0.0;");
    emitLine("long adjacent_count = 0;");
    emitLine("for (int i = 0; i < m; i++) {");
    increaseIndent();
    emitLine("int start = A->row_ptr[i];");
    emitLine("int end = A->row_ptr[i+1];");
    emitLine("int rlen = end - start;");
    emitLine("if (rlen == 0) continue;");
    emitLine("nonempty_rows++;");
    emitLine("int min_col = A->col_idx[start];");
    emitLine("int max_col = A->col_idx[start];");
    emitLine("int runs = 1;");
    emitLine("for (int p = start + 1; p < end; p++) {");
    increaseIndent();
    emitLine("int c = A->col_idx[p];");
    emitLine("if (c < min_col) min_col = c;");
    emitLine("if (c > max_col) max_col = c;");
    emitLine("int gap = A->col_idx[p] - A->col_idx[p-1];");
    emitLine("if (gap < 0) gap = -gap;");
    emitLine("if (gap != 1) runs++;");
    emitLine("else adjacent_count++;");
    emitLine("gap_sum += gap;");
    emitLine("total_gaps++;");
    decreaseIndent();
    emitLine("}");
    emitLine("total_runs += runs;");
    emitLine("total_run_length += rlen;");
    emitLine("span_sum += (max_col - min_col + 1);");
    emitLine("int bw = (i > max_col) ? (i - min_col) : (max_col - i);");
    emitLine("if (bw > bandwidth) bandwidth = bw;");
    decreaseIndent();
    emitLine("}");
    emitLine("double avg_row_span = (nonempty_rows > 0) ? span_sum / nonempty_rows : 0.0;");
    emitLine("double avg_runs_per_row = (nonempty_rows > 0) ? (double)total_runs / nonempty_rows : 0.0;");
    emitLine("double avg_run_length = (total_runs > 0) ? (double)total_run_length / total_runs : 0.0;");
    emitLine("double avg_gap = (total_gaps > 0) ? gap_sum / total_gaps : 0.0;");
    emitLine("double frac_adjacent = (total_gaps > 0) ? (double)adjacent_count / total_gaps : 0.0;");
    emitLine();
    emitLine("// Group 5: Column entropy");
    emitLine("double entropy = 0.0;");
    emitLine("for (int j = 0; j < n; j++) {");
    increaseIndent();
    emitLine("if (col_nnz[j] > 0) {");
    increaseIndent();
    emitLine("double p = (double)col_nnz[j] / nz;");
    emitLine("entropy -= p * log(p);");
    decreaseIndent();
    emitLine("}");
    decreaseIndent();
    emitLine("}");
    emitLine("double norm_entropy = (n > 1) ? entropy / log(n) : 0.0;");
    emitLine();
    emitLine("// Group 6: Cross-row spatial locality");
    emitLine("double col_pair_sum = 0.0;");
    emitLine("for (int j = 0; j < n; j++) {");
    increaseIndent();
    emitLine("col_pair_sum += (double)col_nnz[j] * (col_nnz[j] - 1) / 2.0;");
    decreaseIndent();
    emitLine("}");
    emitLine("double R = (double)m;");
    emitLine("double avg_entry_matches = (R > 1) ? 2.0 * col_pair_sum / (R * (R - 1)) : 0.0;");
    emitLine();
    emitLine("// Print features with FEATURE: prefix");
    emitLine("printf(\"FEATURE: m_rows=%d\\n\", m);");
    emitLine("printf(\"FEATURE: n_cols=%d\\n\", n);");
    emitLine("printf(\"FEATURE: aspect_ratio=%.4f\\n\", aspect_ratio);");
    emitLine("printf(\"FEATURE: nnz=%d\\n\", nz);");
    emitLine("printf(\"FEATURE: density=%.4e\\n\", density);");
    emitLine("printf(\"FEATURE: avg_nnz_row=%.4f\\n\", avg_nnz_row);");
    emitLine("printf(\"FEATURE: avg_nnz_col=%.4f\\n\", avg_nnz_col);");
    emitLine("printf(\"FEATURE: row_variance=%.4f\\n\", row_variance);");
    emitLine("printf(\"FEATURE: row_cv=%.4f\\n\", row_cv);");
    emitLine("printf(\"FEATURE: max_row_length=%d\\n\", max_row_len);");
    emitLine("printf(\"FEATURE: min_row_length=%d\\n\", min_row_len);");
    emitLine("printf(\"FEATURE: col_variance=%.4f\\n\", col_variance);");
    emitLine("printf(\"FEATURE: col_cv=%.4f\\n\", col_cv);");
    emitLine("printf(\"FEATURE: bandwidth=%d\\n\", bandwidth);");
    emitLine("printf(\"FEATURE: avg_row_span=%.2f\\n\", avg_row_span);");
    emitLine("printf(\"FEATURE: avg_runs_per_row=%.2f\\n\", avg_runs_per_row);");
    emitLine("printf(\"FEATURE: avg_run_length=%.2f\\n\", avg_run_length);");
    emitLine("printf(\"FEATURE: avg_gap=%.2f\\n\", avg_gap);");
    emitLine("printf(\"FEATURE: frac_adjacent=%.4f\\n\", frac_adjacent);");
    emitLine("printf(\"FEATURE: normalized_entropy=%.4f\\n\", norm_entropy);");
    emitLine("printf(\"FEATURE: avg_entry_matches=%.2f\\n\", avg_entry_matches);");
    emitLine();
    emitLine("free(col_nnz);");
    decreaseIndent();
    emitLine("}");
    emitLine();
}

void CodeGenerator::emitCSRConversion() {
    emitLine("// Convert COO to CSR (row-major)");
    emitLine("SparseMatrix* mat = (SparseMatrix*)malloc(sizeof(SparseMatrix));");
    emitLine("mat->rows = rows;");
    emitLine("mat->cols = cols;");
    emitLine("mat->nnz = nnz;");
    emitLine("mat->row_ptr = (int*)calloc(rows + 1, sizeof(int));");
    emitLine("mat->col_idx = (int*)malloc(nnz * sizeof(int));");
    emitLine("mat->vals = (double*)malloc(nnz * sizeof(double));");
    emitLine("// CSC aliases (point to same memory as CSR)");
    emitLine("mat->col_ptr = mat->row_ptr;");
    emitLine("mat->row_idx = mat->col_idx;");
    emitLine();
    emitLine("// Count nnz per row");
    emitLine("for (int i = 0; i < nnz; i++) {");
    increaseIndent();
    emitLine("mat->row_ptr[entries[i].r + 1]++;");
    decreaseIndent();
    emitLine("}");
    emitLine();
    emitLine("// Cumulative sum to get row_ptr");
    emitLine("for (int i = 0; i < rows; i++) {");
    increaseIndent();
    emitLine("mat->row_ptr[i + 1] += mat->row_ptr[i];");
    decreaseIndent();
    emitLine("}");
    emitLine();
    emitLine("// Fill col_idx and vals");
    emitLine("int* row_counters = (int*)calloc(rows, sizeof(int));");
    emitLine("for (int i = 0; i < nnz; i++) {");
    increaseIndent();
    emitLine("int row = entries[i].r;");
    emitLine("int dest = mat->row_ptr[row] + row_counters[row];");
    emitLine("mat->col_idx[dest] = entries[i].c;");
    emitLine("mat->vals[dest] = entries[i].v;");
    emitLine("row_counters[row]++;");
    decreaseIndent();
    emitLine("}");
    emitLine();
    emitLine("// Cleanup");
    emitLine("free(entries);");
    emitLine("free(row_counters);");
}

void CodeGenerator::emitCSCConversion() {
    emitLine("// Convert COO to CSC (column-major)");
    emitLine("SparseMatrix* mat = (SparseMatrix*)malloc(sizeof(SparseMatrix));");
    emitLine("mat->rows = rows;");
    emitLine("mat->cols = cols;");
    emitLine("mat->nnz = nnz;");
    emitLine("mat->col_ptr = (int*)calloc(cols + 1, sizeof(int));");
    emitLine("mat->row_idx = (int*)malloc(nnz * sizeof(int));");
    emitLine("mat->vals = (double*)malloc(nnz * sizeof(double));");
    emitLine("// CSR aliases (point to same memory as CSC)");
    emitLine("mat->row_ptr = mat->col_ptr;");
    emitLine("mat->col_idx = mat->row_idx;");
    emitLine();
    emitLine("// Count nnz per column");
    emitLine("for (int i = 0; i < nnz; i++) {");
    increaseIndent();
    emitLine("mat->col_ptr[entries[i].c + 1]++;");
    decreaseIndent();
    emitLine("}");
    emitLine();
    emitLine("// Cumulative sum to get col_ptr");
    emitLine("for (int j = 0; j < cols; j++) {");
    increaseIndent();
    emitLine("mat->col_ptr[j + 1] += mat->col_ptr[j];");
    decreaseIndent();
    emitLine("}");
    emitLine();
    emitLine("// Fill row_idx and vals");
    emitLine("int* col_counters = (int*)calloc(cols, sizeof(int));");
    emitLine("for (int i = 0; i < nnz; i++) {");
    increaseIndent();
    emitLine("int col = entries[i].c;");
    emitLine("int dest = mat->col_ptr[col] + col_counters[col];");
    emitLine("mat->row_idx[dest] = entries[i].r;");
    emitLine("mat->vals[dest] = entries[i].v;");
    emitLine("col_counters[col]++;");
    decreaseIndent();
    emitLine("}");
    emitLine();
    emitLine("// Cleanup");
    emitLine("free(entries);");
    emitLine("free(col_counters);");
}

void CodeGenerator::emitMain() {
    emitLine("// ============================================");
    emitLine("// Main Function");
    emitLine("// ============================================");
    emitLine();

    emitScheduledMain();
}

// The remaining main/harness emitters stay string-built for benchmark compatibility.
// They are moved here unchanged in responsibility, but still orchestrated from generate().

void CodeGenerator::emitScheduledMain() {
    const std::string computeFn = getComputeFunctionName();
    const std::string referenceFn = getReferenceFunctionName();
    const auto& compute = *currentScheduledCompute_;
    const std::string assemblyFn = getAssemblyFunctionName();
    bool sparseOutput = isSparseOutputMode();
    const std::string formatLabel =
        (getPrimarySparseFormat() == ir::Format::CSC) ? "csc" : "csr";

    if (!sparseOutput) {
        emitLine("int main(int argc, char** argv) {");
        increaseIndent();
        emitDenseOutputMain();
        emitLine("return 0;");
        decreaseIndent();
        emitLine("}");
        return;
    }

    emitLine("int main(int argc, char** argv) {");
    increaseIndent();

    if (usesPairwiseSparseInputFlow()) {
        emitLine("if (argc < 3) {");
        increaseIndent();
        emitLine("fprintf(stderr, \"Usage: %s <matrixA.mtx> <matrixB.mtx> [iterations]\\n\", argv[0]);");
        emitLine("return 1;");
        decreaseIndent();
        emitLine("}");
        emitLine();

        emitLine("int iterations = 100;");
        emitLine("if (argc >= 4) {");
        increaseIndent();
        emitLine("iterations = atoi(argv[3]);");
        emitLine("if (iterations <= 0) {");
        increaseIndent();
        emitLine("fprintf(stderr, \"Error: iterations must be > 0\\n\");");
        emitLine("fprintf(stderr, \"Usage: %s <matrixA.mtx> <matrixB.mtx> [iterations]\\n\", argv[0]);");
        emitLine("return 1;");
        decreaseIndent();
        emitLine("}");
        decreaseIndent();
        emitLine("}");
        emitLine();

        emitLine("// Deterministic initialization for reproducible benchmarks");
        emitLine("srand(42);");
        emitLine();

        emitLine("// Load matrices");
        emitLine("SparseMatrix* A = load_matrix_market(argv[1]);");
        emitLine("if (!A) {");
        increaseIndent();
        emitLine("fprintf(stderr, \"Failed to load matrix A from %s\\n\", argv[1]);");
        emitLine("return 1;");
        decreaseIndent();
        emitLine("}");
        emitLine("SparseMatrix* B = load_matrix_market(argv[2]);");
        emitLine("if (!B) {");
        increaseIndent();
        emitLine("fprintf(stderr, \"Failed to load matrix B from %s\\n\", argv[2]);");
        emitLine("free_sparse(A);");
        emitLine("return 1;");
        decreaseIndent();
        emitLine("}");
        emitLine();

        emitLine("// Validate dimension compatibility");
        if (usesNestedSparseProductFlow()) {
            emitLine("if (A->cols != B->rows) {");
            increaseIndent();
            emitLine("fprintf(stderr, \"Error: A->cols (%d) != B->rows (%d) for two-sparse product\\n\", A->cols, B->rows);");
        } else {
            emitLine("if (A->rows != B->rows || A->cols != B->cols) {");
            increaseIndent();
            emitLine("fprintf(stderr, \"Error: A (%dx%d) and B (%dx%d) dimension mismatch\\n\", A->rows, A->cols, B->rows, B->cols);");
        }
        emitLine("free_sparse(A); free_sparse(B);");
        emitLine("return 1;");
        decreaseIndent();
        emitLine("}");
        emitLine();

        emitPairwiseSparseOutputMain(
            computeFn,
            referenceFn,
            assemblyFn,
            formatLabel);
    } else if (usesSampledDenseTraversal()) {
        emitLine("if (argc < 2) {");
        increaseIndent();
        emitLine("fprintf(stderr, \"Usage: %s <matrix.mtx> [K_dim] [iterations]\\n\", argv[0]);");
        emitLine("return 1;");
        decreaseIndent();
        emitLine("}");
        emitLine();

        int K_default = 64;
        for (const auto& tensor : compute.inputs) {
            if (tensor.format == ir::Format::Dense && tensor.dims.size() >= 2) {
                K_default = tensor.dims[1];
                break;
            }
        }

        emitLine("int K = " + std::to_string(K_default) + ";");
        emitLine("if (argc >= 3) {");
        increaseIndent();
        emitLine("K = atoi(argv[2]);");
        emitLine("if (K <= 0) {");
        increaseIndent();
        emitLine("fprintf(stderr, \"Error: K dimension must be > 0\\n\");");
        emitLine("return 1;");
        decreaseIndent();
        emitLine("}");
        decreaseIndent();
        emitLine("}");
        emitLine();

        emitLine("int iterations = 100;");
        emitLine("if (argc >= 4) {");
        increaseIndent();
        emitLine("iterations = atoi(argv[3]);");
        emitLine("if (iterations <= 0) {");
        increaseIndent();
        emitLine("fprintf(stderr, \"Error: iterations must be > 0\\n\");");
        emitLine("return 1;");
        decreaseIndent();
        emitLine("}");
        decreaseIndent();
        emitLine("}");
        emitLine();

        emitLine("// Deterministic initialization for reproducible benchmarks");
        emitLine("srand(42);");
        emitLine();

        emitLine("// Load sampling matrix");
        emitLine("SparseMatrix* A = load_matrix_market(argv[1]);");
        emitLine("if (!A) {");
        increaseIndent();
        emitLine("fprintf(stderr, \"Failed to load matrix\\n\");");
        emitLine("return 1;");
        decreaseIndent();
        emitLine("}");
        emitLine();

        emitSampledOutputMain(computeFn, referenceFn, assemblyFn, formatLabel);
    } else {
        emitLine("if (argc < 2) {");
        increaseIndent();
        emitLine("fprintf(stderr, \"Usage: %s <matrix.mtx> [iterations]\\n\", argv[0]);");
        emitLine("return 1;");
        decreaseIndent();
        emitLine("}");
        emitLine();

        emitLine("int iterations = 100;");
        emitLine("if (argc >= 3) {");
        increaseIndent();
        emitLine("iterations = atoi(argv[2]);");
        emitLine("if (iterations <= 0) {");
        increaseIndent();
        emitLine("fprintf(stderr, \"Error: iterations must be > 0\\n\");");
        emitLine("fprintf(stderr, \"Usage: %s <matrix.mtx> [iterations]\\n\", argv[0]);");
        emitLine("return 1;");
        decreaseIndent();
        emitLine("}");
        decreaseIndent();
        emitLine("}");
        emitLine();

        emitLine("// Deterministic initialization for reproducible benchmarks");
        emitLine("srand(42);");
        emitLine();

        emitLine("// Load matrix");
        emitLine("SparseMatrix* A = load_matrix_market(argv[1]);");
        emitLine("if (!A) {");
        increaseIndent();
        emitLine("fprintf(stderr, \"Failed to load matrix\\n\");");
        emitLine("return 1;");
        decreaseIndent();
        emitLine("}");
        emitLine();

        if (context_.sparseInputs.size() == 1 && context_.denseInputs.empty() &&
            compute.output.indices.size() == 2) {
            const auto& output = getActiveOutput();
            int B_cols = output.dims.size() > 1 ? output.dims[1] : 50;

            emitLine("// Allocate matrices for SpMM");
            emitLine("int B_cols = " + std::to_string(B_cols) + ";");
            emitLine("int C_cols = B_cols;");
            emitLine();

            emitLine("// Allocate B (dense matrix: A->cols x B_cols)");
            emitLine("double** B = (double**)malloc(A->cols * sizeof(double*));");
            emitLine("for (int i = 0; i < A->cols; i++) {");
            increaseIndent();
            emitLine("B[i] = (double*)malloc(B_cols * sizeof(double));");
            decreaseIndent();
            emitLine("}");
            emitLine();

            emitLine("// Allocate C (output matrix: A->rows x C_cols)");
            emitLine("double** C = (double**)malloc(A->rows * sizeof(double*));");
            emitLine("double** C_ref = (double**)malloc(A->rows * sizeof(double*));");
            emitLine("for (int i = 0; i < A->rows; i++) {");
            increaseIndent();
            emitLine("C[i] = (double*)malloc(C_cols * sizeof(double));");
            emitLine("C_ref[i] = (double*)malloc(C_cols * sizeof(double));");
            decreaseIndent();
            emitLine("}");
            emitLine();

            emitLine("// Initialize B with random values");
            emitLine("for (int i = 0; i < A->cols; i++) {");
            increaseIndent();
            emitLine("for (int j = 0; j < B_cols; j++) {");
            increaseIndent();
            emitLine("B[i][j] = (double)rand() / RAND_MAX;");
            decreaseIndent();
            emitLine("}");
            decreaseIndent();
            emitLine("}");
            emitLine();

            emitLine("// Initialize C to zero");
            emitLine("for (int i = 0; i < A->rows; i++) {");
            increaseIndent();
            emitLine("memset(C[i], 0, C_cols * sizeof(double));");
            emitLine("memset(C_ref[i], 0, C_cols * sizeof(double));");
            decreaseIndent();
            emitLine("}");
            emitLine();

            emitLine("// Warmup");
            emitLine(computeFn + "(A, B, C, C_cols);");
            emitLine();

            emitLine("// Benchmark with per-iteration timing");
            emitLine("double* iter_times = (double*)malloc(iterations * sizeof(double));");
            emitLine();
            emitLine("for (int iter = 0; iter < iterations; iter++) {");
            increaseIndent();
            emitLine("// Reset C");
            emitLine("for (int i = 0; i < A->rows; i++) {");
            increaseIndent();
            emitLine("memset(C[i], 0, C_cols * sizeof(double));");
            decreaseIndent();
            emitLine("}");
            emitLine("double iter_start = get_time_ms();");
            emitLine(computeFn + "(A, B, C, C_cols);");
            emitLine("double iter_end = get_time_ms();");
            emitLine("iter_times[iter] = iter_end - iter_start;");
            decreaseIndent();
            emitLine("}");
            emitLine();

            emitTimingStatistics();

            emitLine("// Verify correctness");
            emitLine(referenceFn + "(A, B, C_ref, C_cols);");
            emitLine("double max_error = 0.0;");
            emitLine("for (int i = 0; i < A->rows; i++) {");
            increaseIndent();
            emitLine("for (int j = 0; j < C_cols; j++) {");
            increaseIndent();
            emitLine("double err = C[i][j] - C_ref[i][j];");
            emitLine("if (err < 0) err = -err;");
            emitLine("if (err > max_error) max_error = err;");
            decreaseIndent();
            emitLine("}");
            decreaseIndent();
            emitLine("}");
            emitLine();

            emitLine("// Report results");
            emitLine("printf(\"Matrix: %s (%d x %d, %d nnz)\\n\", argv[1], A->rows, A->cols, A->nnz);");
            emitLine("printf(\"Iterations: %d\\n\", iterations);");
            emitLine("printf(\"Total time: %.2f ms\\n\", total_time);");
            emitLine("printf(\"Avg time per iteration: %.4f ms\\n\", avg_time);");
            emitLine("printf(\"Min time per iteration: %.4f ms\\n\", min_time);");
            emitLine("printf(\"Max time per iteration: %.4f ms\\n\", max_time);");
            emitLine("printf(\"Stddev time: %.4f ms\\n\", stddev);");
            emitLine("printf(\"Variance: %.2f%%\\n\", variance_pct);");
            emitLine("printf(\"Max error vs reference: %e\\n\", max_error);");
            emitLine();

            emitLine("compute_features(A);");
            emitLine();

            emitLine("// Cleanup");
            emitLine("free(iter_times);");
            emitLine("for (int i = 0; i < A->cols; i++) free(B[i]);");
            emitLine("free(B);");
            emitLine("for (int i = 0; i < A->rows; i++) {");
            increaseIndent();
            emitLine("free(C[i]);");
            emitLine("free(C_ref[i]);");
            decreaseIndent();
            emitLine("}");
            emitLine("free(C);");
            emitLine("free(C_ref);");
            emitLine("free_sparse(A);");
            emitLine();
        } else {
            emitLine("// Allocate vectors");
            emitLine("double* x = (double*)malloc(A->cols * sizeof(double));");
            emitLine("double* y = (double*)malloc(A->rows * sizeof(double));");
            emitLine("double* y_ref = (double*)malloc(A->rows * sizeof(double));");
            emitLine();

            emitLine("// Initialize x with random values");
            emitLine("for (int i = 0; i < A->cols; i++) {");
            increaseIndent();
            emitLine("x[i] = (double)rand() / RAND_MAX;");
            decreaseIndent();
            emitLine("}");
            emitLine("memset(y, 0, A->rows * sizeof(double));");
            emitLine("memset(y_ref, 0, A->rows * sizeof(double));");
            emitLine();

            emitLine("// Warmup");
            emitLine(computeFn + "(A, x, y);");
            emitLine();

            emitLine("// Benchmark with per-iteration timing");
            emitLine("double* iter_times = (double*)malloc(iterations * sizeof(double));");
            emitLine();
            emitLine("for (int iter = 0; iter < iterations; iter++) {");
            increaseIndent();
            emitLine("memset(y, 0, A->rows * sizeof(double));");
            emitLine("double iter_start = get_time_ms();");
            emitLine(computeFn + "(A, x, y);");
            emitLine("double iter_end = get_time_ms();");
            emitLine("iter_times[iter] = iter_end - iter_start;");
            decreaseIndent();
            emitLine("}");
            emitLine();

            emitTimingStatistics();

            emitLine("// Verify correctness");
            emitLine(referenceFn + "(A, x, y_ref);");
            emitLine("double max_error = 0.0;");
            emitLine("for (int i = 0; i < A->rows; i++) {");
            increaseIndent();
            emitLine("double err = y[i] - y_ref[i];");
            emitLine("if (err < 0) err = -err;");
            emitLine("if (err > max_error) max_error = err;");
            decreaseIndent();
            emitLine("}");
            emitLine();

            emitLine("// Report results");
            emitLine("printf(\"Matrix: %s (%d x %d, %d nnz)\\n\", argv[1], A->rows, A->cols, A->nnz);");
            emitLine("printf(\"Iterations: %d\\n\", iterations);");
            emitLine("printf(\"Total time: %.2f ms\\n\", total_time);");
            emitLine("printf(\"Avg time per iteration: %.4f ms\\n\", avg_time);");
            emitLine("printf(\"Min time per iteration: %.4f ms\\n\", min_time);");
            emitLine("printf(\"Max time per iteration: %.4f ms\\n\", max_time);");
            emitLine("printf(\"Stddev time: %.4f ms\\n\", stddev);");
            emitLine("printf(\"Variance: %.2f%%\\n\", variance_pct);");
            emitLine("printf(\"Max error vs reference: %e\\n\", max_error);");
            emitLine();

            emitLine("compute_features(A);");
            emitLine();

            emitLine("// Cleanup");
            emitLine("free(iter_times);");
            emitLine("free(x);");
            emitLine("free(y);");
            emitLine("free(y_ref);");
            emitLine("free_sparse(A);");
            emitLine();
        }
    }

    emitLine("return 0;");
    decreaseIndent();
    emitLine("}");
}

void CodeGenerator::emitDenseOutputMain() {
    const auto& inputs = getActiveInputs();
    const auto& output = getActiveOutput();
    if (inputs.empty() && output.name.empty()) return;

    const std::string computeFn = getComputeFunctionName();
    const std::string referenceFn = getReferenceFunctionName();
    const size_t explicitDimCount = context_.explicitDimensions.size();

    std::vector<const ir::Tensor*> sparseInputs;
    std::vector<const ir::Tensor*> denseInputs;
    for (const auto& tensor : inputs) {
        if (tensor.format != ir::Format::Dense) {
            sparseInputs.push_back(&tensor);
        } else {
            denseInputs.push_back(&tensor);
        }
    }

    int numMtxFiles = std::max(1, (int)sparseInputs.size());

    emitLine("if (argc < " + std::to_string(1 + numMtxFiles) + ") {");
    increaseIndent();
    std::string usage = "fprintf(stderr, \"Usage: %s";
    if (numMtxFiles == 1) {
        usage += " <matrix.mtx>";
    } else {
        for (int i = 0; i < numMtxFiles; i++) {
            std::string suffix = (i < (int)sparseInputs.size()) ? sparseInputs[i]->name
                                                                : std::to_string(i + 1);
            usage += " <matrix" + suffix + ".mtx>";
        }
    }
    if (usesSampledDenseTraversal()) {
        for (const auto& dim : context_.explicitDimensions) {
            usage += (dim.paramName == "N_k") ? " [K_dim]" : (" [" + dim.paramName + "]");
        }
    }
    usage += " [iterations]\\n\", argv[0]);";
    emitLine(usage);
    emitLine("return 1;");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitLine("int iterations = 100;");
    const int iterationsArgIndex = static_cast<int>(
        1 + numMtxFiles + (usesSampledDenseTraversal() ? explicitDimCount : 0));
    emitLine("if (argc >= " + std::to_string(iterationsArgIndex + 1) + ") {");
    increaseIndent();
    emitLine("iterations = atoi(argv[" + std::to_string(iterationsArgIndex) + "]);");
    emitLine("if (iterations <= 0) {");
        increaseIndent();
        emitLine("fprintf(stderr, \"Error: iterations must be > 0\\n\");");
        emitLine("return 1;");
        decreaseIndent();
        emitLine("}");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitLine("// Deterministic initialization for reproducible benchmarks");
    emitLine("srand(42);");
    emitLine();

    for (int i = 0; i < (int)sparseInputs.size(); i++) {
        const auto& tensor = *sparseInputs[i];
        emitLine("// Load sparse matrix " + tensor.name);
        emitLine("SparseMatrix* " + tensor.name + " = load_matrix_market(argv[" +
                 std::to_string(i + 1) + "]);");
        emitLine("if (!" + tensor.name + ") {");
        increaseIndent();
        emitLine("fprintf(stderr, \"Failed to load matrix " + tensor.name + "\\n\");");
        emitLine("return 1;");
        decreaseIndent();
        emitLine("}");
        emitLine();
    }

    std::set<std::string> emittedDimVars;
    for (size_t dimIndex = 0; dimIndex < context_.explicitDimensions.size(); ++dimIndex) {
        const auto& dim = context_.explicitDimensions[dimIndex];
        emitLine("int " + dim.paramName + " = " + std::to_string(dim.defaultValue) + ";");
        if (usesSampledDenseTraversal()) {
            emitLine("if (argc >= " + std::to_string(2 + numMtxFiles + dimIndex) + ") {");
            increaseIndent();
            emitLine(dim.paramName + " = atoi(argv[" + std::to_string(1 + numMtxFiles + dimIndex) + "]);");
            emitLine("if (" + dim.paramName + " <= 0) {");
            increaseIndent();
            emitLine("fprintf(stderr, \"Error: " + dim.paramName + " must be > 0\\n\");");
            emitLine("return 1;");
            decreaseIndent();
            emitLine("}");
            decreaseIndent();
            emitLine("}");
        }
        emittedDimVars.insert(dim.paramName);
    }
    if (!emittedDimVars.empty()) emitLine();

    if (sparseInputs.size() == 2) {
        if (usesNestedSparseProductFlow()) {
            emitLine("if (" + sparseInputs[0]->name + "->cols != " + sparseInputs[1]->name + "->rows) {");
            increaseIndent();
            emitLine("fprintf(stderr, \"Error: " + sparseInputs[0]->name + "->cols != " +
                     sparseInputs[1]->name + "->rows (%d != %d)\\n\", " +
                     sparseInputs[0]->name + "->cols, " + sparseInputs[1]->name + "->rows);");
            emitLine("free_sparse(" + sparseInputs[0]->name + ");");
            emitLine("free_sparse(" + sparseInputs[1]->name + ");");
            emitLine("return 1;");
            decreaseIndent();
            emitLine("}");
        } else {
            emitLine("if (" + sparseInputs[0]->name + "->rows != " + sparseInputs[1]->name +
                     "->rows || " + sparseInputs[0]->name + "->cols != " +
                     sparseInputs[1]->name + "->cols) {");
            increaseIndent();
            emitLine("fprintf(stderr, \"Error: dimension mismatch between " +
                     sparseInputs[0]->name + " and " + sparseInputs[1]->name +
                     " (%dx%d vs %dx%d)\\n\", " +
                     sparseInputs[0]->name + "->rows, " + sparseInputs[0]->name +
                     "->cols, " + sparseInputs[1]->name + "->rows, " +
                     sparseInputs[1]->name + "->cols);");
            emitLine("free_sparse(" + sparseInputs[0]->name + ");");
            emitLine("free_sparse(" + sparseInputs[1]->name + ");");
            emitLine("return 1;");
            decreaseIndent();
            emitLine("}");
        }
        emitLine();
    }

    for (const auto& tensor : denseInputs) {
        if (tensor->indices.size() >= 2) {
            std::string rowBound = getIndexBoundExpr(tensor->indices[0]);
            std::string colBound = getIndexBoundExpr(tensor->indices[1]);
            emitLine("// Allocate dense matrix " + tensor->name);
            emitLine("double** " + tensor->name + " = (double**)malloc(" + rowBound + " * sizeof(double*));");
            emitLine("for (int _i = 0; _i < " + rowBound + "; _i++) {");
            increaseIndent();
            emitLine(tensor->name + "[_i] = (double*)malloc(" + colBound + " * sizeof(double));");
            emitLine("for (int _j = 0; _j < " + colBound + "; _j++) {");
            increaseIndent();
            emitLine(tensor->name + "[_i][_j] = (double)rand() / RAND_MAX;");
            decreaseIndent();
            emitLine("}");
            decreaseIndent();
            emitLine("}");
        } else {
            std::string sizeBound = getIndexBoundExpr(tensor->indices[0]);
            emitLine("// Allocate dense vector " + tensor->name);
            emitLine("double* " + tensor->name + " = (double*)malloc(" + sizeBound + " * sizeof(double));");
            emitLine("for (int _i = 0; _i < " + sizeBound + "; _i++) {");
            increaseIndent();
            emitLine(tensor->name + "[_i] = (double)rand() / RAND_MAX;");
            decreaseIndent();
            emitLine("}");
        }
        emitLine();
    }

    if (output.indices.size() >= 2) {
        std::string rowBound = getIndexBoundExpr(output.indices[0]);
        std::string colBound = getIndexBoundExpr(output.indices[1]);
        emitLine("// Allocate output matrix " + output.name);
        emitLine("double** " + output.name + " = (double**)malloc(" + rowBound + " * sizeof(double*));");
        emitLine("double** " + output.name + "_ref = (double**)malloc(" + rowBound + " * sizeof(double*));");
        emitLine("for (int _i = 0; _i < " + rowBound + "; _i++) {");
        increaseIndent();
        emitLine(output.name + "[_i] = (double*)calloc(" + colBound + ", sizeof(double));");
        emitLine(output.name + "_ref[_i] = (double*)calloc(" + colBound + ", sizeof(double));");
        decreaseIndent();
        emitLine("}");
    } else {
        std::string sizeBound = getIndexBoundExpr(output.indices[0]);
        emitLine("// Allocate output vector " + output.name);
        emitLine("double* " + output.name + " = (double*)calloc(" + sizeBound + ", sizeof(double));");
        emitLine("double* " + output.name + "_ref = (double*)calloc(" + sizeBound + ", sizeof(double));");
    }
    emitLine();

    std::string callArgs;
    std::set<std::string> seenTensors;
    for (const auto& tensor : inputs) {
        if (seenTensors.count(tensor.name)) continue;
        seenTensors.insert(tensor.name);
        if (!callArgs.empty()) callArgs += ", ";
        callArgs += tensor.name;
    }
    if (!seenTensors.count(output.name)) {
        if (!callArgs.empty()) callArgs += ", ";
        callArgs += output.name;
    }
    for (const auto& dimVar : emittedDimVars) {
        callArgs += ", " + dimVar;
    }

    std::string refCallArgs;
    seenTensors.clear();
    for (const auto& tensor : inputs) {
        if (seenTensors.count(tensor.name)) continue;
        seenTensors.insert(tensor.name);
        if (!refCallArgs.empty()) refCallArgs += ", ";
        refCallArgs += tensor.name;
    }
    if (!seenTensors.count(output.name)) {
        if (!refCallArgs.empty()) refCallArgs += ", ";
        refCallArgs += output.name + "_ref";
    }
    for (const auto& dimVar : emittedDimVars) {
        refCallArgs += ", " + dimVar;
    }

    emitLine("// Warmup");
    emitLine(computeFn + "(" + callArgs + ");");
    emitLine();

    emitLine("// Benchmark with per-iteration timing");
    emitLine("double* iter_times = (double*)malloc(iterations * sizeof(double));");
    emitLine();
    emitLine("for (int iter = 0; iter < iterations; iter++) {");
    increaseIndent();

    if (output.indices.size() >= 2) {
        std::string rowBound = getIndexBoundExpr(output.indices[0]);
        std::string colBound = getIndexBoundExpr(output.indices[1]);
        emitLine("for (int _i = 0; _i < " + rowBound + "; _i++) {");
        increaseIndent();
        emitLine("memset(" + output.name + "[_i], 0, " + colBound + " * sizeof(double));");
        decreaseIndent();
        emitLine("}");
    } else {
        std::string sizeBound = getIndexBoundExpr(output.indices[0]);
        emitLine("memset(" + output.name + ", 0, " + sizeBound + " * sizeof(double));");
    }

    emitLine("double iter_start = get_time_ms();");
    emitLine(computeFn + "(" + callArgs + ");");
    emitLine("double iter_end = get_time_ms();");
    emitLine("iter_times[iter] = iter_end - iter_start;");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitTimingStatistics();

    emitLine("// Verify correctness");
    emitLine(referenceFn + "(" + refCallArgs + ");");
    emitLine("double max_error = 0.0;");

    if (output.indices.size() >= 2) {
        std::string rowBound = getIndexBoundExpr(output.indices[0]);
        std::string colBound = getIndexBoundExpr(output.indices[1]);
        emitLine("for (int _i = 0; _i < " + rowBound + "; _i++) {");
        increaseIndent();
        emitLine("for (int _j = 0; _j < " + colBound + "; _j++) {");
        increaseIndent();
        emitLine("double err = " + output.name + "[_i][_j] - " + output.name + "_ref[_i][_j];");
        emitLine("if (err < 0) err = -err;");
        emitLine("if (err > max_error) max_error = err;");
        decreaseIndent();
        emitLine("}");
        decreaseIndent();
        emitLine("}");
    } else {
        std::string sizeBound = getIndexBoundExpr(output.indices[0]);
        emitLine("for (int _i = 0; _i < " + sizeBound + "; _i++) {");
        increaseIndent();
        emitLine("double err = " + output.name + "[_i] - " + output.name + "_ref[_i];");
        emitLine("if (err < 0) err = -err;");
        emitLine("if (err > max_error) max_error = err;");
        decreaseIndent();
        emitLine("}");
    }
    emitLine();

    emitLine("// Report results");
    if (sparseInputs.size() == 1) {
        emitLine("printf(\"Matrix: %s (%d x %d, %d nnz)\\n\", argv[1], " +
                 sparseInputs[0]->name + "->rows, " +
                 sparseInputs[0]->name + "->cols, " +
                 sparseInputs[0]->name + "->nnz);");
    } else {
        for (size_t i = 0; i < sparseInputs.size(); i++) {
            const auto& tensor = sparseInputs[i]->name;
            emitLine("printf(\"Matrix " + tensor + ": %s (%d x %d, %d nnz)\\n\", argv[" +
                     std::to_string(i + 1) + "], " + tensor + "->rows, " + tensor +
                     "->cols, " + tensor + "->nnz);");
        }
    }
    emitLine("printf(\"Iterations: %d\\n\", iterations);");
    emitLine("printf(\"Total time: %.2f ms\\n\", total_time);");
    emitLine("printf(\"Avg time per iteration: %.4f ms\\n\", avg_time);");
    emitLine("printf(\"Min time per iteration: %.4f ms\\n\", min_time);");
    emitLine("printf(\"Max time per iteration: %.4f ms\\n\", max_time);");
    emitLine("printf(\"Stddev time: %.4f ms\\n\", stddev);");
    emitLine("printf(\"Variance: %.2f%%\\n\", variance_pct);");
    emitLine("printf(\"Max error vs reference: %e\\n\", max_error);");
    emitLine();

    if (!sparseInputs.empty()) {
        emitLine("compute_features(" + sparseInputs[0]->name + ");");
        emitLine();
    }

    emitLine("// Cleanup");
    emitLine("free(iter_times);");

    for (const auto& tensor : denseInputs) {
        if (tensor->indices.size() >= 2) {
            std::string rowBound = getIndexBoundExpr(tensor->indices[0]);
            emitLine("for (int _i = 0; _i < " + rowBound + "; _i++) free(" + tensor->name + "[_i]);");
            emitLine("free(" + tensor->name + ");");
        } else {
            emitLine("free(" + tensor->name + ");");
        }
    }

    if (output.indices.size() >= 2) {
        std::string rowBound = getIndexBoundExpr(output.indices[0]);
        emitLine("for (int _i = 0; _i < " + rowBound + "; _i++) {");
        increaseIndent();
        emitLine("free(" + output.name + "[_i]);");
        emitLine("free(" + output.name + "_ref[_i]);");
        decreaseIndent();
        emitLine("}");
        emitLine("free(" + output.name + ");");
        emitLine("free(" + output.name + "_ref);");
    } else {
        emitLine("free(" + output.name + ");");
        emitLine("free(" + output.name + "_ref);");
    }

    for (const auto& tensor : sparseInputs) {
        emitLine("free_sparse(" + tensor->name + ");");
    }
    emitLine();
}

void CodeGenerator::emitPairwiseSparseOutputMain(const std::string& computeFn,
                                                 const std::string& referenceFn,
                                                 const std::string& assemblyFn,
                                                 const std::string& formatLabel) {
    emitLine("int rows = A->rows;");
    if (usesNestedSparseProductFlow()) {
        emitLine("int cols = B->cols;");
    } else {
        emitLine("int cols = A->cols;");
    }
    emitLine();

    if (isSparseOutputMode()) {
        emitLine("// Assemble sparse structure once (outside timed region)");
        emitLine("SparseMatrix* C = (SparseMatrix*)calloc(1, sizeof(SparseMatrix));");
        emitLine(assemblyFn + "(A, B, C);");
        emitLine("double* C_ref_vals = (double*)calloc((size_t)C->nnz, sizeof(double));");
        emitLine();

        emitLine("// Warmup");
        emitLine("zero_sparse_values(C);");
        emitLine(computeFn + "(A, B, C);");
        emitLine();

        emitLine("// Benchmark with per-iteration timing (compute only)");
        emitLine("double* iter_times = (double*)malloc(iterations * sizeof(double));");
        emitLine();
        emitLine("for (int iter = 0; iter < iterations; iter++) {");
        increaseIndent();
        emitLine("zero_sparse_values(C);");
        emitLine("double iter_start = get_time_ms();");
        emitLine(computeFn + "(A, B, C);");
        emitLine("double iter_end = get_time_ms();");
        emitLine("iter_times[iter] = iter_end - iter_start;");
        decreaseIndent();
        emitLine("}");
        emitLine();

        emitTimingStatistics();

        emitLine("// Verify correctness with structure-aligned reference values");
        emitLine("memset(C_ref_vals, 0, (size_t)C->nnz * sizeof(double));");
        emitLine(referenceFn + "(A, B, C, C_ref_vals);");
        emitLine("double max_error = max_abs_error_sparse(C->vals, C_ref_vals, C->nnz);");
        emitLine();

        emitLine("// Report results");
        emitLine("printf(\"Matrix A: %s (%d x %d, %d nnz)\\n\", argv[1], A->rows, A->cols, A->nnz);");
        emitLine("printf(\"Matrix B: %s (%d x %d, %d nnz)\\n\", argv[2], B->rows, B->cols, B->nnz);");
        emitLine("printf(\"Format: " + formatLabel + "\\n\");");
        emitLine("printf(\"Output C nnz: %d\\n\", C->nnz);");
        emitLine("printf(\"Iterations: %d\\n\", iterations);");
        emitLine("printf(\"Total time: %.2f ms\\n\", total_time);");
        emitLine("printf(\"Avg time per iteration: %.4f ms\\n\", avg_time);");
        emitLine("printf(\"Min time per iteration: %.4f ms\\n\", min_time);");
        emitLine("printf(\"Max time per iteration: %.4f ms\\n\", max_time);");
        emitLine("printf(\"Stddev time: %.4f ms\\n\", stddev);");
        emitLine("printf(\"Variance: %.2f%%\\n\", variance_pct);");
        emitLine("printf(\"Max error vs reference: %e\\n\", max_error);");
        emitLine();

        emitLine("compute_features(A);");
        emitLine();

        emitLine("// Cleanup");
        emitLine("free(iter_times);");
        emitLine("free(C_ref_vals);");
        emitLine("free_sparse(C);");
        emitLine("free_sparse(A);");
        emitLine("free_sparse(B);");
        emitLine();
        return;
    }

    emitLine("// Allocate output matrices C and C_ref (dense 2D)");
    emitLine("double** C = (double**)malloc(rows * sizeof(double*));");
    emitLine("double** C_ref = (double**)malloc(rows * sizeof(double*));");
    emitLine("for (int i = 0; i < rows; i++) {");
    increaseIndent();
    emitLine("C[i] = (double*)calloc(cols, sizeof(double));");
    emitLine("C_ref[i] = (double*)calloc(cols, sizeof(double));");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitLine("// Warmup");
    emitLine(computeFn + "(A, B, C);");
    emitLine();

    emitLine("// Benchmark with per-iteration timing");
    emitLine("double* iter_times = (double*)malloc(iterations * sizeof(double));");
    emitLine();
    emitLine("for (int iter = 0; iter < iterations; iter++) {");
    increaseIndent();
    emitLine("for (int i = 0; i < rows; i++) {");
    increaseIndent();
    emitLine("memset(C[i], 0, cols * sizeof(double));");
    decreaseIndent();
    emitLine("}");
    emitLine("double iter_start = get_time_ms();");
    emitLine(computeFn + "(A, B, C);");
    emitLine("double iter_end = get_time_ms();");
    emitLine("iter_times[iter] = iter_end - iter_start;");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitTimingStatistics();

    emitLine("// Verify correctness");
    emitLine(referenceFn + "(A, B, C_ref);");
    emitLine("double max_error = 0.0;");
    emitLine("for (int i = 0; i < rows; i++) {");
    increaseIndent();
    emitLine("for (int j = 0; j < cols; j++) {");
    increaseIndent();
    emitLine("double err = C[i][j] - C_ref[i][j];");
    emitLine("if (err < 0) err = -err;");
    emitLine("if (err > max_error) max_error = err;");
    decreaseIndent();
    emitLine("}");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitLine("// Report results");
    emitLine("printf(\"Matrix A: %s (%d x %d, %d nnz)\\n\", argv[1], A->rows, A->cols, A->nnz);");
    emitLine("printf(\"Matrix B: %s (%d x %d, %d nnz)\\n\", argv[2], B->rows, B->cols, B->nnz);");
    emitLine("printf(\"Iterations: %d\\n\", iterations);");
    emitLine("printf(\"Total time: %.2f ms\\n\", total_time);");
    emitLine("printf(\"Avg time per iteration: %.4f ms\\n\", avg_time);");
    emitLine("printf(\"Min time per iteration: %.4f ms\\n\", min_time);");
    emitLine("printf(\"Max time per iteration: %.4f ms\\n\", max_time);");
    emitLine("printf(\"Stddev time: %.4f ms\\n\", stddev);");
    emitLine("printf(\"Variance: %.2f%%\\n\", variance_pct);");
    emitLine("printf(\"Max error vs reference: %e\\n\", max_error);");
    emitLine();

    emitLine("compute_features(A);");
    emitLine();

    emitLine("// Cleanup");
    emitLine("free(iter_times);");
    emitLine("for (int i = 0; i < rows; i++) {");
    increaseIndent();
    emitLine("free(C[i]);");
    emitLine("free(C_ref[i]);");
    decreaseIndent();
    emitLine("}");
    emitLine("free(C);");
    emitLine("free(C_ref);");
    emitLine("free_sparse(A);");
    emitLine("free_sparse(B);");
    emitLine();
}

void CodeGenerator::emitSampledOutputMain(const std::string& computeFn,
                                          const std::string& referenceFn,
                                          const std::string& assemblyFn,
                                          const std::string& formatLabel) {
    emitLine("// SDDMM: C[i,j] = S[i,j] * (D[i,k] * E[k,j])");
    emitLine("SparseMatrix* S = A;");
    emitLine("int rows = S->rows;");
    emitLine("int cols = S->cols;");
    emitLine();

    emitLine("// Allocate D (rows x K)");
    emitLine("double** D = (double**)malloc(rows * sizeof(double*));");
    emitLine("for (int i = 0; i < rows; i++) {");
    increaseIndent();
    emitLine("D[i] = (double*)malloc(K * sizeof(double));");
    emitLine("for (int k = 0; k < K; k++) D[i][k] = (double)rand() / RAND_MAX;");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitLine("// Allocate E (K x cols)");
    emitLine("double** E = (double**)malloc(K * sizeof(double*));");
    emitLine("for (int k = 0; k < K; k++) {");
    increaseIndent();
    emitLine("E[k] = (double*)malloc(cols * sizeof(double));");
    emitLine("for (int j = 0; j < cols; j++) E[k][j] = (double)rand() / RAND_MAX;");
    decreaseIndent();
    emitLine("}");
    emitLine();

    std::string dimArgs;
    for (const auto& dim : context_.explicitDimensions) {
        dimArgs += ", " + dim.paramName;
    }

    if (isSparseOutputMode()) {
        emitLine("SparseMatrix* C = (SparseMatrix*)calloc(1, sizeof(SparseMatrix));");
        emitLine(assemblyFn + "(S, C);");
        emitLine("double* C_ref_vals = (double*)calloc((size_t)C->nnz, sizeof(double));");
        emitLine();

        emitLine("// Warmup");
        emitLine("zero_sparse_values(C);");
        emitLine(computeFn + "(S, D, E, C" + dimArgs + ");");
        emitLine();

        emitLine("// Benchmark with per-iteration timing (compute only)");
        emitLine("double* iter_times = (double*)malloc(iterations * sizeof(double));");
        emitLine();
        emitLine("for (int iter = 0; iter < iterations; iter++) {");
        increaseIndent();
        emitLine("zero_sparse_values(C);");
        emitLine("double iter_start = get_time_ms();");
        emitLine(computeFn + "(S, D, E, C" + dimArgs + ");");
        emitLine("double iter_end = get_time_ms();");
        emitLine("iter_times[iter] = iter_end - iter_start;");
        decreaseIndent();
        emitLine("}");
        emitLine();

        emitTimingStatistics();

        emitLine("// Verify correctness with structure-aligned reference values");
        emitLine("memset(C_ref_vals, 0, (size_t)C->nnz * sizeof(double));");
        emitLine(referenceFn + "(S, D, E, C, C_ref_vals" + dimArgs + ");");
        emitLine("double max_error = max_abs_error_sparse(C->vals, C_ref_vals, C->nnz);");
        emitLine();

        emitLine("// Report results");
        emitLine("printf(\"Matrix S: %s (%d x %d, %d nnz)\\n\", argv[1], S->rows, S->cols, S->nnz);");
        emitLine("printf(\"Format: " + formatLabel + "\\n\");");
        emitLine("printf(\"K dimension: %d\\n\", K);");
        emitLine("printf(\"Output C nnz: %d\\n\", C->nnz);");
        emitLine("printf(\"Iterations: %d\\n\", iterations);");
        emitLine("printf(\"Total time: %.2f ms\\n\", total_time);");
        emitLine("printf(\"Avg time per iteration: %.4f ms\\n\", avg_time);");
        emitLine("printf(\"Min time per iteration: %.4f ms\\n\", min_time);");
        emitLine("printf(\"Max time per iteration: %.4f ms\\n\", max_time);");
        emitLine("printf(\"Stddev time: %.4f ms\\n\", stddev);");
        emitLine("printf(\"Variance: %.2f%%\\n\", variance_pct);");
        emitLine("printf(\"Max error vs reference: %e\\n\", max_error);");
        emitLine();

        emitLine("compute_features(S);");
        emitLine();

        emitLine("// Cleanup");
        emitLine("free(iter_times);");
        emitLine("for (int i = 0; i < rows; i++) free(D[i]);");
        emitLine("for (int k = 0; k < K; k++) free(E[k]);");
        emitLine("free(D);");
        emitLine("free(E);");
        emitLine("free(C_ref_vals);");
        emitLine("free_sparse(C);");
        emitLine("free_sparse(S);");
        emitLine();
        return;
    }

    emitLine("// Allocate output matrices C and C_ref (dense 2D)");
    emitLine("double** C = (double**)malloc(rows * sizeof(double*));");
    emitLine("double** C_ref = (double**)malloc(rows * sizeof(double*));");
    emitLine("for (int i = 0; i < rows; i++) {");
    increaseIndent();
    emitLine("C[i] = (double*)calloc(cols, sizeof(double));");
    emitLine("C_ref[i] = (double*)calloc(cols, sizeof(double));");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitLine("// Warmup");
    emitLine(computeFn + "(S, D, E, C" + dimArgs + ");");
    emitLine();

    emitLine("// Benchmark with per-iteration timing");
    emitLine("double* iter_times = (double*)malloc(iterations * sizeof(double));");
    emitLine();
    emitLine("for (int iter = 0; iter < iterations; iter++) {");
    increaseIndent();
    emitLine("for (int i = 0; i < rows; i++) {");
    increaseIndent();
    emitLine("memset(C[i], 0, cols * sizeof(double));");
    decreaseIndent();
    emitLine("}");
    emitLine("double iter_start = get_time_ms();");
    emitLine(computeFn + "(S, D, E, C" + dimArgs + ");");
    emitLine("double iter_end = get_time_ms();");
    emitLine("iter_times[iter] = iter_end - iter_start;");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitTimingStatistics();

    emitLine("// Verify correctness");
    emitLine(referenceFn + "(S, D, E, C_ref" + dimArgs + ");");
    emitLine("double max_error = 0.0;");
    emitLine("for (int i = 0; i < rows; i++) {");
    increaseIndent();
    emitLine("for (int j = 0; j < cols; j++) {");
    increaseIndent();
    emitLine("double err = C[i][j] - C_ref[i][j];");
    emitLine("if (err < 0) err = -err;");
    emitLine("if (err > max_error) max_error = err;");
    decreaseIndent();
    emitLine("}");
    decreaseIndent();
    emitLine("}");
    emitLine();

    emitLine("// Report results");
    emitLine("printf(\"Matrix: %s (%d x %d, %d nnz)\\n\", argv[1], S->rows, S->cols, S->nnz);");
    emitLine("printf(\"K dimension: %d\\n\", K);");
    emitLine("printf(\"Iterations: %d\\n\", iterations);");
    emitLine("printf(\"Total time: %.2f ms\\n\", total_time);");
    emitLine("printf(\"Avg time per iteration: %.4f ms\\n\", avg_time);");
    emitLine("printf(\"Min time per iteration: %.4f ms\\n\", min_time);");
    emitLine("printf(\"Max time per iteration: %.4f ms\\n\", max_time);");
    emitLine("printf(\"Stddev time: %.4f ms\\n\", stddev);");
    emitLine("printf(\"Variance: %.2f%%\\n\", variance_pct);");
    emitLine("printf(\"Max error vs reference: %e\\n\", max_error);");
    emitLine();

    emitLine("compute_features(S);");
    emitLine();

    emitLine("// Cleanup");
    emitLine("free(iter_times);");
    emitLine("for (int i = 0; i < rows; i++) { free(D[i]); free(C[i]); free(C_ref[i]); }");
    emitLine("for (int k = 0; k < K; k++) free(E[k]);");
    emitLine("free(D); free(E); free(C); free(C_ref);");
    emitLine("free_sparse(S);");
    emitLine();
}

}  // namespace codegen
